# Configuration Starfun API centrale
messages:
  prefix: "&6[Starfun]&r"
npctesting:
  default-arena: "default"
  default-weapon: "sword" # sword ou bow
help:
  header: "&eAide Starfun API"
bungeecord:
  enabled: false
  routes:
    rush: "starfun-rush"
    hikabrain: "starfun-hikabrain"
    skywars: "starfun-skywars"
    freecube: "starfun-freecube"
